============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/jake/Development/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, repeat-0.9.1
collected 11 items

series/series_test.py .FF........                                        [100%]

=================================== FAILURES ===================================
_______________ SeriesTest.test_slice_length_cannot_be_negative ________________

self = <series_test.SeriesTest testMethod=test_slice_length_cannot_be_negative>

    def test_slice_length_cannot_be_negative(self):
        with self.assertRaises(ValueError) as err:
            slices("123", -1)
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "slice length cannot be negative")
E       AssertionError: 'slice length cannot be zero or negative' != 'slice length cannot be negative'
E       - slice length cannot be zero or negative
E       ?                       --------
E       + slice length cannot be negative

series/series_test.py:60: AssertionError
_________________ SeriesTest.test_slice_length_cannot_be_zero __________________

self = <series_test.SeriesTest testMethod=test_slice_length_cannot_be_zero>

    def test_slice_length_cannot_be_zero(self):
        with self.assertRaises(ValueError) as err:
            slices("12345", 0)
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "slice length cannot be zero")
E       AssertionError: 'slice length cannot be zero or negative' != 'slice length cannot be zero'
E       - slice length cannot be zero or negative
E       ?                            ------------
E       + slice length cannot be zero

series/series_test.py:54: AssertionError
=========================== short test summary info ============================
FAILED series/series_test.py::SeriesTest::test_slice_length_cannot_be_negative
FAILED series/series_test.py::SeriesTest::test_slice_length_cannot_be_zero - ...
========================= 2 failed, 9 passed in 0.04s ==========================
