============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/jake/Development/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, repeat-0.9.1
collected 7 items

exercises/practice/hangman/hangman_test.py ..F....                       [100%]

=================================== FAILURES ===================================
_____ HangmanTests.test_feeding_a_correct_letter_twice_counts_as_a_failure _____

self = <hangman_test.HangmanTests testMethod=test_feeding_a_correct_letter_twice_counts_as_a_failure>

    def test_feeding_a_correct_letter_twice_counts_as_a_failure(self):
        game = Hangman('foobar')
    
        game.guess('b')
        self.assertEqual(game.get_status(), hangman.STATUS_ONGOING)
        self.assertEqual(game.remaining_guesses, 9)
        self.assertEqual(game.get_masked_word(), '___b__')
    
        game.guess('b')
        self.assertEqual(game.get_status(), hangman.STATUS_ONGOING)
>       self.assertEqual(game.remaining_guesses, 8)
E       AssertionError: 9 != 8

exercises/practice/hangman/hangman_test.py:55: AssertionError
=========================== short test summary info ============================
FAILED exercises/practice/hangman/hangman_test.py::HangmanTests::test_feeding_a_correct_letter_twice_counts_as_a_failure
========================= 1 failed, 6 passed in 0.03s ==========================
