============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.3.0
rootdir: /home/jake/Development/mentat/tests/benchmarks/repos/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, asyncio-0.21.1, xdist-3.3.1
asyncio: mode=strict
collected 5 items

exercises/practice/error-handling/error_handling_test.py .F.F.           [100%]

=================================== FAILURES ===================================
_____ ErrorHandlingTest.test_filelike_objects_are_closed_without_exception _____

self = <error_handling_test.ErrorHandlingTest testMethod=test_filelike_objects_are_closed_without_exception>

    def test_filelike_objects_are_closed_without_exception(self):
        filelike_object = FileLike(fail_something=False)
>       er.filelike_objects_are_closed_on_exception(filelike_object)

exercises/practice/error-handling/error_handling_test.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filelike_object = <test_utils.FileLike object at 0x7f4beb8e0370>

    def filelike_objects_are_closed_on_exception(filelike_object):
        try:
            filelike_object.open()
            filelike_object.do_something()
        except Exception as e:
            filelike_object.close()
            raise e
        finally:
>           if not filelike_object.is_closed:  # Assuming the correct attribute is `is_closed`
E           AttributeError: 'FileLike' object has no attribute 'is_closed'

exercises/practice/error-handling/error_handling.py:33: AttributeError
_____________________ ErrorHandlingTest.test_return_tuple ______________________

self = <error_handling_test.ErrorHandlingTest testMethod=test_return_tuple>

    def test_return_tuple(self):
        successful_result, result = er.handle_error_by_returning_tuple('1')
>       self.assertIs(successful_result, True,
                      'Valid input should be successful')
E       AssertionError: False is not True : Valid input should be successful

exercises/practice/error-handling/error_handling_test.py:20: AssertionError
=========================== short test summary info ============================
FAILED exercises/practice/error-handling/error_handling_test.py::ErrorHandlingTest::test_filelike_objects_are_closed_without_exception
FAILED exercises/practice/error-handling/error_handling_test.py::ErrorHandlingTest::test_return_tuple
========================= 2 failed, 3 passed in 0.06s ==========================
