============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/jake/Development/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, repeat-0.9.1
collected 6 items

exercises/practice/nth-prime/nth_prime_test.py .....F                    [100%]

=================================== FAILURES ===================================
__________________ NthPrimeTest.test_there_is_no_zeroth_prime __________________

self = <nth_prime_test.NthPrimeTest testMethod=test_there_is_no_zeroth_prime>

    def test_there_is_no_zeroth_prime(self):
        with self.assertRaises(ValueError) as err:
            prime(0)
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "there is no zeroth prime")
E       AssertionError: 'Input number must be greater than or equal to 1' != 'there is no zeroth prime'
E       - Input number must be greater than or equal to 1
E       + there is no zeroth prime

exercises/practice/nth-prime/nth_prime_test.py:34: AssertionError
=========================== short test summary info ============================
FAILED exercises/practice/nth-prime/nth_prime_test.py::NthPrimeTest::test_there_is_no_zeroth_prime
========================= 1 failed, 5 passed in 1.93s ==========================
