============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/jake/Development/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, repeat-0.9.1
collected 10 items

exercises/practice/pascals-triangle/pascals_triangle_test.py .....F...F  [100%]

=================================== FAILURES ===================================
________________ PascalsTriangleTest.test_solution_is_recursive ________________

self = <pascals_triangle_test.PascalsTriangleTest testMethod=test_solution_is_recursive>

    def test_solution_is_recursive(self):
        with self.assertRaises(RecursionError) as err:
            rows(sys.getrecursionlimit() + 10)
>           self.assertEqual(type(err.exception), RecursionError)
E           AttributeError: '_AssertRaisesContext' object has no attribute 'exception'

exercises/practice/pascals-triangle/pascals_triangle_test.py:61: AttributeError
______________________ PascalsTriangleTest.test_zero_rows ______________________

self = <pascals_triangle_test.PascalsTriangleTest testMethod=test_zero_rows>

    def test_zero_rows(self):
>       self.assertEqual(rows(0), TRIANGLE[:0])

exercises/practice/pascals-triangle/pascals_triangle_test.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

row_count = 0

    def rows(row_count):
        if row_count <= 0:
>           raise ValueError("row_count must be a positive integer")
E           ValueError: row_count must be a positive integer

exercises/practice/pascals-triangle/pascals_triangle.py:3: ValueError
=========================== short test summary info ============================
FAILED exercises/practice/pascals-triangle/pascals_triangle_test.py::PascalsTriangleTest::test_solution_is_recursive
FAILED exercises/practice/pascals-triangle/pascals_triangle_test.py::PascalsTriangleTest::test_zero_rows
========================= 2 failed, 8 passed in 0.16s ==========================
